# Configuration du port de l'application backend
server.port=8080

# Configuration de la connexion à la base de données PostgreSQL
# Note : Vous devrez créer la base de données nommée 'riad_db' dans pgAdmin ou psql avant de lancer l'application.
# Modifiez 'postgres' par votre identifiant et mot de passe de base de données si nécessaire.
spring.datasource.url=jdbc:postgresql://localhost:5432/riad_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' mettra à jour la structure des tables PostgreSQL en fonction de nos entités Java
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL générées par Hibernate dans la console (pratique pour le débogage)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Désactiver l'écriture des dates comme timestamps de sorte qu'elles soient lisibles (ex: "2026-08-01")
spring.jackson.serialization.write-dates-as-timestamps=false

# Configuration Cloudinary (Stockage gratuit de photos)
# Remplacer par vos propres clés récupérées depuis votre console Cloudinary (https://cloudinary.com)
cloudinary.cloud-name=mgmnml6e
cloudinary.api-key=182159963577494
cloudinary.api-secret=BKYkM88ThJzNjdwjvVUeFvcTKPQ

# Taille limite d'upload de fichiers (images des Riads/chambres)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuration de l'envoi d'e-mails réels (SMTP Gmail)
#Décommentez et configurez ces lignes pour envoyer de vrais emails à vos clients :
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elamranihouda540@gmail.com
spring.mail.password=sfsr ecqd huqv ygxc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
