"use client";

import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  fr: {
    // Header/Navbar
    nav_riads: "Nos Riads",
    nav_services: "Nos Services",
    nav_catalogue: "Catalogue",
    nav_reservations: "Mes Réservations",
    hello: "Bonjour,",
    espace_client: "Mon Espace Client",
    logout: "Déconnexion",
    login: "Connexion",
    register: "S'inscrire",
    
    // Hero
    hero_subtitle: "Une immersion marocaine authentique",
    hero_title: "Trouvez le Riad de vos Rêves au Maroc",
    hero_desc: "Réservez une chambre unique, plusieurs suites pour votre famille, ou privatisez un riad entier à Marrakech, Fès ou Essaouira.",

    // Search & Filters
    search_destination: "Destination (Ville)",
    search_anywhere: "Toutes les villes",
    search_title: "Rechercher",
    search_pax_label: "Nombre de Pax",
    search_pax_placeholder: "2 Pax",
    search_budget_label: "Budget Max (MAD)",
    search_dates_duration: "Dates de Séjour (Arrivée - Départ)",

    // Main / Riads Section
    riads_title: "Riads Authentiques Populaires",
    riads_desc: "Découvrez notre sélection de Riads validés par notre équipe, prêts à vous accueillir.",
    loading_riads: "Chargement des riads...",
    no_riads: "Aucun riad disponible dans cette ville pour le moment.",
    chambres_count: "chambres",
    per_night: "par nuit",
    mad_per_night: "MAD par nuit",

    // Services Section
    services_title: "Nos Services Premium & Rituels",
    services_desc: "Profitez d'une gamme de services exclusifs disponibles dans nos riads pour sublimer votre séjour :",
    service_spa_title: "Espace Spa & Bien-être",
    service_spa_desc: "Offrez-vous un moment de détente absolue avec des massages aux huiles essentielles d'argan bio et des soins du visage apaisants.",
    service_hammam_title: "Hammam Traditionnel",
    service_hammam_desc: "Découvrez le rituel ancestral du gommage au savon noir marocain et gant de kessa traditionnel pour purifier votre corps.",
    service_traiteur_title: "Service Traiteur & Gastronomie",
    service_traiteur_desc: "Dégustez des plats typiques marocains (tajines, couscous, pastillas) cuisinés avec amour par nos chefs à partir d'ingrédients frais et locaux.",

    // Footer
    footer_desc: "La plateforme de référence pour réserver des séjours uniques dans les plus beaux riads traditionnels du Maroc.",
    footer_destinations: "Destinations",
    footer_platform: "Plateforme",
    footer_newsletter: "Newsletter",
    newsletter_desc: "Abonnez-vous pour recevoir des offres exclusives.",
    newsletter_placeholder: "Votre email",
    newsletter_btn: "S'abonner",
    newsletter_success: "Abonnement réussi !",
    footer_rights: "© 2026 MoroccoRiads. Tous droits réservés.",
    footer_motto: "L'art de l'hospitalité marocaine au cœur de la médina.",

    // Auth (Login)
    login_title: "Ravi de vous revoir !",
    login_subtitle: "Connectez-vous pour accéder à votre espace personnalisé.",
    login_email: "Adresse email",
    login_password: "Mot de passe",
    login_btn: "Se connecter",
    login_loading: "Connexion en cours...",
    login_new: "Nouveau sur MoroccoRiads ?",
    login_create: "Créer un compte",
    login_err_required: "Veuillez remplir tous les champs obligatoires.",
    login_success: "Connexion réussie ! Redirection vers votre espace...",

    // Auth (Register)
    register_title: "Créer votre compte",
    register_subtitle: "Rejoignez-nous pour réserver ou proposer vos Riads au Maroc.",
    register_nom: "Nom",
    register_prenom: "Prénom",
    register_email: "Adresse email",
    register_phone: "Téléphone (Optionnel)",
    register_password: "Mot de passe",
    register_loading: "Création du compte...",
    register_btn: "Créer mon compte",
    register_already: "Vous avez déjà un compte ?",
    register_login: "Se connecter",
    register_err_required: "Veuillez remplir tous les champs obligatoires.",
    register_err_password_length: "Le mot de passe doit contenir au moins 6 caractères.",
    register_success: "Inscription réussie ! Connexion automatique...",

    // Client space layout / loading
    loading_space: "Chargement de votre espace...",
    guest_user: "Visiteur / Invité",
    
    // Client Catalogue
    catalogue_title: "Découvrez nos Riads",
    catalogue_subtitle: "Découvrez notre sélection de riads d'exception et réservez votre séjour.",
    no_riads_zone: "Aucun riad disponible pour ces critères de recherche.",
    photos_count: "photos",
    view_rooms: "Voir les Chambres & Disponibilités",
    starting_from: "À partir de",
    rooms_count: "chambre(s)",

    // Client Reservations
    reservations_title: "Mes Réservations",
    reservations_subtitle: "Retrouvez ici toutes vos réservations passées et en cours.",
    no_reservations: "Vous n'avez pas encore de réservations enregistrées.",
    explore_riads: "Explorer les Riads",
    from: "Du",
    to: "au",
    total: "Total :",
    entire_riad: "Riad entier",
    cancel: "Annuler",
    leave_review: "Laisser un avis",
    review_title: "Avis —",
    your_rating: "Votre note",
    your_comment: "Votre commentaire (optionnel)",
    comment_placeholder: "Racontez votre expérience dans ce riad...",
    submit_review: "Soumettre mon avis",
    sending_review: "Envoi en cours...",
    res_cancelled: "Réservation annulée.",
    review_success: "Avis soumis avec succès ! Merci pour votre retour.",
    status_pending: "En attente",
    status_confirmed: "Confirmée",
    status_cancelled: "Annulée",
    status_refused: "Refusée",
    confirm_cancel: "Êtes-vous sûr de vouloir annuler cette réservation ?",

    // Riad Detail & Booking
    back_to_catalogue: "Retour au catalogue",
    riad_not_found: "Riad non trouvé.",
    service_spa: "Spa & Bien-être",
    service_hammam: "Hammam Traditionnel",
    service_catering: "Service Traiteur",
    reviews_label: "avis",
    entire_riad_reserved: "Riad entier réservé",
    privatization_unavailable: "Privatisation indisponible (chambres occupées)",
    privatize_entire_riad: "Privatiser le Riad entier",
    available_rooms: "Chambres & Suites",
    no_rooms_available: "Aucune chambre disponible pour ce Riad.",
    filter_only_available: "Chambres disponibles uniquement",
    filter_all_types: "Tous les types",
    filter_type_label: "Type de chambre :",
    room_available_badge: "Disponible",
    room_reserved_badge: "Réservé",
    room_occupied_badge: "Occupé",
    room_unavailable_badge: "Indisponible",
    max_capacity: "Capacité :",
    pax_unit: "Pax",
    travelers: "Pax",
    book_this_room: "Réserver cette chambre",
    pending_validation: "Réservé (En attente confirmation)",
    room_occupied_btn: "Occupé (Réservation validée)",
    traveler_reviews: "Avis Voyageurs",
    no_reviews_yet: "Aucun avis pour l'instant. Soyez le premier à partager votre séjour !",
    check_in_date: "Date d'arrivée",
    check_out_date: "Date de départ",
    payment_method: "Mode de paiement",
    credit_card: "Carte Bancaire",
    paypal_secure: "PayPal",
    on_site_cash: "Paiement sur place",
    nights_label: "Nuits",
    unit_price: "Tarif unitaire",
    confirm_and_book: "Confirmer et Réserver",
    creating_booking: "Réservation en cours...",
    err_fill_dates: "Veuillez renseigner vos dates de séjour.",
    err_date_order: "La date de départ doit être postérieure à la date d'arrivée.",
    err_dates_unavailable: "La chambre ou le Riad est déjà indisponible pour ces dates.",
    success_booking_pending: "Demande de réservation enregistrée avec succès !",
    success_booking_confirmed: "Félicitations ! Votre réservation est confirmée.",
    guest_info_title: "Vos Coordonnées",
    guest_nom: "Nom",
    guest_prenom: "Prénom",
    guest_email: "Adresse Email",
    guest_phone: "Numéro de Téléphone",
    onsite_warning_title: "Information Importante (Paiement sur place)",
    onsite_warning_body: "Pour confirmer définitivement votre réservation, vous devez verser une avance (acompte) ou vous présenter à l'établissement avant le jour de votre arrivée (jour J). Sans versement d'avance ou confirmation préalable avant le jour J, la réservation sera automatiquement annulée le jour J.",
    calendar_title: "Calendrier de Disponibilité",
    calendar_legend_available: "Disponible",
    calendar_legend_reserved: "Réservé (Attente propriétaire)",
    calendar_legend_occupied: "Occupé (Confirmé)",
    merchant: "Marchand",
    amount: "Montant",
    paypal_email: "Adresse email PayPal",
    pay: "Payer",
    cancel_and_return: "Annuler et retourner sur le site",
    processing_payment: "Traitement du paiement en cours...",
    dont_close_window: "Veuillez ne pas fermer cette fenêtre. Connexion sécurisée au réseau bancaire.",
    payment_authorized: "Paiement Autorisé avec Succès !",
    auto_redirect: "Redirection automatique vers l'application...",
    paypal_tx_id: "Transaction PayPal ID:",
    secure_connection: "Connexion sécurisée",

    // Espace Propriétaire / Owner Space
    owner_space: "Espace Propriétaire",
    owner_dashboard: "Tableau de Bord",
    owner_dashboard_title: "Tableau de Bord Opérationnel",
    owner_reservations: "Réservations & Check-in",
    owner_rooms: "Gestion des Chambres",
    owner_riads: "Gestion des Riads",
    owner_profile_settings: "Profil & Paramètres",
    owner_property_management: "GESTION ÉTABLISSEMENT",
    owner_account_settings: "COMPTE & PARAMÈTRES",
    owner_planning_title: "Planning des Disponibilités (Semaine)",
    owner_btn_prev: "Précédent",
    owner_btn_today: "Aujourd'hui",
    owner_btn_next: "Suivant",
    owner_room_free: "Libre",
    owner_room_occupied: "Occupé",
    owner_room_arrival: "Arrivée",
    owner_room_past: "Passé",
    owner_room_today_closed: "Jour même",
    owner_legend_free: "Chambre Libre (Cliquer pour réserver)",
    owner_legend_occupied: "Chambre Occupée (Cliquer pour détails)",
    owner_legend_arrival: "Arrivée / Check-in prévu ce jour",
    owner_kpi_riads: "Riads Enregistrés",
    owner_kpi_rooms: "Chambres Disponibles",
    owner_kpi_occupancy: "Taux d'Occupation",
    owner_kpi_confirmed: "Séjours Confirmés",
    owner_kpi_revenue: "Chiffre d'Affaires",
    owner_active: "Actif",
    owner_stay_unit: "Séjour(s)",
    owner_room_unit: "Chambres",
    owner_riads_unit: "Riad(s)",
    owner_save_changes: "Enregistrer les Modifications",
    owner_new_direct_booking: "Nouvelle Réservation Directe",
    owner_checkin_title: "Check-in & Enregistrement Client",
    owner_good_morning: "Bonjour",
    owner_good_evening: "Bonsoir",
    owner_reservations_mgmt: "Gestion des Réservations & Check-in",
    owner_booking_details: "Détails de la Réservation",
    owner_stay_dates: "DATES DU SÉJOUR",
    owner_total_amount: "MONTANT TOTAL",
    owner_do_checkin: "Effectuer le Check-in",
    owner_view_police_sheet: "Voir Fiche de Police",
    owner_close: "Fermer",
    owner_filter_all: "Toutes",
    owner_filter_pending: "En Attente",
    owner_filter_arrivals: "Arrivées du Jour",
    owner_filter_confirmed: "Confirmées",
    owner_filter_refused: "Refusées",
    owner_th_id: "ID Réservation",
    owner_th_client: "Client & Contact",
    owner_th_dates: "Dates Séjour",
    owner_th_amount: "Montant",
    owner_th_status: "Statut",
    owner_th_checkin: "Check-in Client",
    owner_th_actions: "Actions Opérationnelles",
    owner_btn_sheet: "Fiche",
    owner_btn_refuse: "Refuser",
    owner_add_room: "Ajouter une Chambre",
    owner_riad_sheet: "Fiche Riad",
    owner_save: "Enregistrer",
    owner_riad_name: "Nom du Riad",
    owner_riad_address: "Adresse dans la Médina",
    owner_commercial_desc: "Description commerciale",
    owner_privatization_price: "Tarif Privatisation Riad Entier (MAD / nuit)",
    owner_offered_services: "Services Proposés aux Voyageurs",
    owner_manager_email: "Email Gérant",
    owner_security_password: "Sécurité & Mot de Passe",
    owner_new_password: "Nouveau Mot de Passe",
    owner_confirm_password: "Confirmer Mot de Passe",
    owner_no_rooms: "Aucune chambre configurée pour ce Riad.",
    owner_no_res_filter: "Aucune réservation trouvée pour ce filtre.",
    owner_btn_edit: "Modifier",
    owner_btn_hide: "Masquer",
    owner_btn_publish: "Publier",
    owner_btn_delete_room: "Supprimer la Chambre",
    owner_room_status_occupied: "Occupée",
    owner_room_status_reserved: "Réservée (Sur place)",
    owner_room_status_available: "Disponible",
    owner_room_current_state: "État actuel :",
    owner_room_pers: "pers.",
    owner_room_delete_confirm_title: "Supprimer la Chambre ?",
    owner_room_delete_confirm_msg: "Êtes-vous sûr de vouloir supprimer la chambre",
    owner_btn_yes_delete: "Oui, Supprimer",
    owner_btn_cancel: "Annuler",
    owner_add_room_title: "Ajouter une nouvelle chambre",
    owner_edit_room_title: "Modifier la chambre",
    owner_room_name_label: "Nom de la chambre *",
    owner_room_type_label: "Type de chambre",
    owner_room_type_simple: "Chambre Simple",
    owner_room_type_double: "Chambre Double",
    owner_room_type_suite: "Suite de Luxe",
    owner_room_type_familiale: "Suite Familiale",
    owner_room_price_label: "Prix / nuit (MAD) *",
    owner_room_photo_label: "Photo (depuis votre disque local)",
    owner_room_change_photo_label: "Changer la photo de la chambre (depuis votre disque local)",
    owner_btn_create_room: "Créer la Chambre",
    owner_btn_save_changes_room: "Sauvegarder les modifications",
    owner_direct_booking_subtitle: "Enregistrez un client sur place (Walk-in) ou réservation par téléphone",
    owner_establishment_label: "Établissement (Riad) *",
    owner_booking_type_label: "Type de Réservation",
    owner_type_single_room: "Chambre Individuelle",
    owner_type_entire_riad: "Riad Entier (Exclusif)",
    owner_select_room_prompt: "-- Choisir une chambre --",
    owner_checkin_date_label: "Date d'Arrivée (Check-in) *",
    owner_checkout_date_label: "Date de Départ (Check-out) *",
    owner_guest_lastname: "Nom du Client *",
    owner_guest_firstname: "Prénom du Client *",
    owner_payment_mode_label: "Mode de Règlement",
    owner_pay_onsite: "Sur Place (Espèces / TPE)",
    owner_pay_card_confirmed: "Carte Bancaire (Confirmée)",
    owner_btn_confirm_booking: "Confirmer la Réservation",
    owner_checkin_modal_title: "Check-in & Enregistrement Client",
    owner_checkin_arrival_at: "Enregistrement d'arrivée au",
    owner_booking_id_short: "N° Réservation",
    owner_accommodation_label: "Hébergement",
    owner_legal_id_info: "Informations d'Identité Légale (Fiche de Police)",
    owner_id_type_label: "Type de pièce *",
    owner_id_cin: "CIN Marocaine",
    owner_id_passport: "Passeport Étranger",
    owner_id_residence: "Carte de Séjour",
    owner_id_number_label: "Numéro de pièce (CIN / Passeport) *",
    owner_nationality_label: "Nationalité",
    owner_birthdate_label: "Date de naissance",
    owner_occupants_count_label: "Nombre d'occupants",
    owner_contact_phone_label: "Téléphone de contact",
    owner_guest_email_label: "Email du voyageur",
    owner_confirm_payment_onsite: "Confirmer le règlement du séjour",
    owner_collect_mode: "Mode d'encaissement :",
    owner_cash: "Espèces",
    owner_card_pos: "Carte TPE",
    owner_bank_transfer: "Virement",
    owner_checkin_remarks_label: "Remarques / Demandes d'accueil (ex: Clés remises, Lit bébé, Petit-déjeuner)",
    owner_checkin_remarks_placeholder: "Notes internes pour le séjour du client...",
    owner_btn_confirm_checkin: "Confirmer & Valider le Check-in",
    owner_police_voucher_title: "Fiche d'Enregistrement Client (Check-in Validé)",
    owner_btn_print_sheet: "Imprimer la Fiche",
    owner_police_sheet_doc_title: "Fiche Individuelle de Séjour & d'Accueil",
    owner_police_sheet_doc_sub: "Enregistrement officiel de l'hôte à l'arrivée (Hospitalité Marocaine)",
    owner_guest_details_box: "Renseignements du Client",
    owner_stay_details_box: "Détails du Séjour",
    owner_guest_signature: "Signature du Voyageur / Hôte",
    owner_establishment_signature: "Cachet & Signature de l'Établissement",
    owner_read_approved: "Lu et approuvé",
    owner_done: "Effectué",
    owner_not_done: "Non effectué"
  },
  en: {
    // Header/Navbar
    nav_riads: "Our Riads",
    nav_services: "Our Services",
    nav_catalogue: "Catalog",
    nav_reservations: "My Reservations",
    hello: "Hello,",
    espace_client: "My Client Space",
    logout: "Log Out",
    login: "Log In",
    register: "Sign Up",
    
    // Hero
    hero_subtitle: "An authentic Moroccan immersion",
    hero_title: "Find Your Dream Riad in Morocco",
    hero_desc: "Book a unique room, multiple suites for your family, or privatize an entire riad in Marrakech, Fez or Essaouira.",

    // Search
    search_destination: "Destination (City)",
    search_anywhere: "All cities",
    search_title: "Search",
    search_pax_label: "Number of Pax",
    search_pax_placeholder: "2 Pax",
    search_budget_label: "Max Budget (MAD)",
    search_dates_duration: "Stay Dates (Check-in - Check-out)",

    // Main / Riads Section
    riads_title: "Popular Authentic Riads",
    riads_desc: "Discover our selection of Riads verified by our team, ready to welcome you.",
    loading_riads: "Loading riads...",
    no_riads: "No riads available in this city at the moment.",
    chambres_count: "rooms",
    per_night: "per night",
    mad_per_night: "MAD per night",

    // Services Section
    services_title: "Our Premium Services & Rituals",
    services_desc: "Enjoy a range of exclusive services available in our riads to enhance your stay:",
    service_spa_title: "Spa & Wellness Area",
    service_spa_desc: "Treat yourself to a moment of absolute relaxation with massages with organic argan essential oils and soothing facials.",
    service_hammam_title: "Traditional Hammam",
    service_hammam_desc: "Discover the ancestral ritual of scrubbing with Moroccan black soap and a traditional kessa glove to purify your body.",
    service_traiteur_title: "Catering & Gastronomy Service",
    service_traiteur_desc: "Taste typical Moroccan dishes (tajines, couscous, pastillas) cooked with love by our chefs from fresh, local ingredients.",

    // Footer
    footer_desc: "The leading platform for booking unique stays in the most beautiful traditional riads in Morocco.",
    footer_destinations: "Destinations",
    footer_platform: "Platform",
    footer_newsletter: "Newsletter",
    newsletter_desc: "Subscribe to receive exclusive offers.",
    newsletter_placeholder: "Your email",
    newsletter_btn: "Subscribe",
    newsletter_success: "Subscription successful!",
    footer_rights: "© 2026 MoroccoRiads. All rights reserved.",
    footer_motto: "The art of Moroccan hospitality in the heart of the medina.",

    // Auth (Login)
    login_title: "Welcome back!",
    login_subtitle: "Log in to access your personalized space.",
    login_email: "Email address",
    login_password: "Password",
    login_btn: "Log In",
    login_loading: "Logging in...",
    login_new: "New to MoroccoRiads?",
    login_create: "Create an account",
    login_err_required: "Please fill in all required fields.",
    login_success: "Login successful! Redirecting to your space...",

    // Auth (Register)
    register_title: "Create your account",
    register_subtitle: "Join us to book or offer your Riads in Morocco.",
    register_nom: "Last name",
    register_prenom: "First name",
    register_email: "Email address",
    register_phone: "Phone (Optional)",
    register_password: "Password",
    register_loading: "Creating account...",
    register_btn: "Create my account",
    register_already: "Already have an account?",
    register_login: "Log in",
    register_err_required: "Please fill in all required fields.",
    register_err_password_length: "Password must be at least 6 characters long.",
    register_success: "Registration successful! Logging in...",

    // Client space layout / loading
    loading_space: "Loading your space...",
    guest_user: "Guest Visitor",
    
    // Client Catalog
    catalogue_title: "Discover our Riads",
    catalogue_subtitle: "Discover our curated collection of exceptional riads and book your stay.",
    no_riads_zone: "No riads available for these search criteria.",
    photos_count: "photos",
    view_rooms: "View Rooms & Availability",
    starting_from: "Starting from",
    rooms_count: "room(s)",

    // Client Reservations
    reservations_title: "My Reservations",
    reservations_subtitle: "Find all your past and current reservations here.",
    no_reservations: "You do not have any reservations yet.",
    explore_riads: "Explore Riads",
    from: "From",
    to: "to",
    total: "Total:",
    entire_riad: "Entire Riad",
    cancel: "Cancel",
    leave_review: "Leave a review",
    review_title: "Review —",
    your_rating: "Your rating",
    your_comment: "Your comment (optional)",
    comment_placeholder: "Tell us about your experience in this riad...",
    submit_review: "Submit my review",
    sending_review: "Submitting...",
    res_cancelled: "Reservation cancelled.",
    review_success: "Review submitted successfully! Thank you for your feedback.",
    status_pending: "Pending",
    status_confirmed: "Confirmed",
    status_cancelled: "Cancelled",
    status_refused: "Refused",
    confirm_cancel: "Are you sure you want to cancel this reservation?",

    // Riad Detail & Booking
    back_to_catalogue: "Back to catalog",
    riad_not_found: "Riad not found.",
    service_spa: "Spa & Wellness",
    service_hammam: "Traditional Hammam",
    service_catering: "Catering Service",
    reviews_label: "reviews",
    entire_riad_reserved: "Entire Riad reserved",
    privatization_unavailable: "Privatization unavailable (occupied rooms)",
    privatize_entire_riad: "Privatize the entire Riad",
    available_rooms: "Rooms & Suites",
    no_rooms_available: "No rooms available for this Riad.",
    filter_only_available: "Only available rooms",
    filter_all_types: "All types",
    filter_type_label: "Room type:",
    room_available_badge: "Available",
    room_reserved_badge: "Reserved",
    room_occupied_badge: "Occupied",
    room_unavailable_badge: "Unavailable",
    max_capacity: "Capacity:",
    pax_unit: "Pax",
    travelers: "Pax",
    book_this_room: "Book this room",
    pending_validation: "Reserved (Pending confirmation)",
    room_occupied_btn: "Occupied (Booking confirmed)",
    traveler_reviews: "Traveler Reviews",
    no_reviews_yet: "No reviews yet. Be the first to share your stay!",
    check_in_date: "Check-in date",
    check_out_date: "Check-out date",
    payment_method: "Payment method",
    credit_card: "Credit Card",
    paypal_secure: "PayPal",
    on_site_cash: "On-site payment",
    nights_label: "Nights",
    unit_price: "Unit price",
    confirm_and_book: "Confirm and Book",
    creating_booking: "Booking in progress...",
    err_fill_dates: "Please enter your stay dates.",
    err_date_order: "Check-out date must be after check-in date.",
    err_dates_unavailable: "The room or Riad is already unavailable for these dates.",
    success_booking_pending: "Reservation request registered successfully!",
    success_booking_confirmed: "Congratulations! Your reservation is confirmed.",
    guest_info_title: "Your Details",
    guest_nom: "Last Name",
    guest_prenom: "First Name",
    guest_email: "Email Address",
    guest_phone: "Phone Number",
    onsite_warning_title: "Important Information (On-Site Payment)",
    onsite_warning_body: "To definitively guarantee and confirm your booking, you must pay an advance deposit or visit the property before your arrival day (Day J). Without an advance deposit or prior confirmation before Day J, the booking will be automatically cancelled on Day J.",
    calendar_title: "Availability Calendar",
    calendar_legend_available: "Available",
    calendar_legend_reserved: "Reserved (Owner approval pending)",
    calendar_legend_occupied: "Occupied (Confirmed)",
    merchant: "Merchant",
    amount: "Amount",
    paypal_email: "PayPal email address",
    pay: "Pay",
    cancel_and_return: "Cancel and return to site",
    processing_payment: "Processing payment...",
    dont_close_window: "Please do not close this window. Secure connection to banking network.",
    payment_authorized: "Payment Authorized Successfully!",
    auto_redirect: "Automatic redirection to application...",
    paypal_tx_id: "PayPal Transaction ID:",
    secure_connection: "Secure connection",

    // Espace Propriétaire / Owner Space
    owner_space: "Owner Space",
    owner_dashboard: "Dashboard",
    owner_dashboard_title: "Operational Dashboard",
    owner_reservations: "Reservations & Check-in",
    owner_rooms: "Room Management",
    owner_riads: "Riad Management",
    owner_profile_settings: "Profile & Settings",
    owner_property_management: "PROPERTY MANAGEMENT",
    owner_account_settings: "ACCOUNT & SETTINGS",
    owner_planning_title: "Weekly Availability Planning",
    owner_btn_prev: "Previous",
    owner_btn_today: "Today",
    owner_btn_next: "Next",
    owner_room_free: "Available",
    owner_room_occupied: "Occupied",
    owner_room_arrival: "Arrival",
    owner_room_past: "Past",
    owner_room_today_closed: "Same day",
    owner_legend_free: "Available Room (Click to book)",
    owner_legend_occupied: "Occupied Room (Click for details)",
    owner_legend_arrival: "Arrival / Check-in scheduled today",
    owner_kpi_riads: "Registered Riads",
    owner_kpi_rooms: "Available Rooms",
    owner_kpi_occupancy: "Occupancy Rate",
    owner_kpi_confirmed: "Confirmed Stays",
    owner_kpi_revenue: "Turnover (Revenue)",
    owner_active: "Active",
    owner_stay_unit: "Stay(s)",
    owner_room_unit: "Rooms",
    owner_riads_unit: "Riad(s)",
    owner_save_changes: "Save Changes",
    owner_new_direct_booking: "New Direct Booking",
    owner_checkin_title: "Check-in & Guest Registration",
    owner_good_morning: "Good morning",
    owner_good_evening: "Good evening",
    owner_reservations_mgmt: "Reservation & Check-in Management",
    owner_booking_details: "Booking Details",
    owner_stay_dates: "STAY DATES",
    owner_total_amount: "TOTAL AMOUNT",
    owner_do_checkin: "Perform Check-in",
    owner_view_police_sheet: "View Police Sheet",
    owner_close: "Close",
    owner_filter_all: "All",
    owner_filter_pending: "Pending",
    owner_filter_arrivals: "Today's Arrivals",
    owner_filter_confirmed: "Confirmed",
    owner_filter_refused: "Refused",
    owner_th_id: "Booking ID",
    owner_th_client: "Guest & Contact",
    owner_th_dates: "Stay Dates",
    owner_th_amount: "Amount",
    owner_th_status: "Status",
    owner_th_checkin: "Guest Check-in",
    owner_th_actions: "Operational Actions",
    owner_btn_sheet: "Voucher",
    owner_btn_refuse: "Refuse",
    owner_add_room: "Add a Room",
    owner_riad_sheet: "Riad Profile",
    owner_save: "Save",
    owner_riad_name: "Riad Name",
    owner_riad_address: "Address in Medina",
    owner_commercial_desc: "Commercial Description",
    owner_privatization_price: "Entire Riad Privatization Rate (MAD / night)",
    owner_offered_services: "Services Offered to Guests",
    owner_manager_email: "Manager Email",
    owner_security_password: "Security & Password",
    owner_new_password: "New Password",
    owner_confirm_password: "Confirm Password",
    owner_no_rooms: "No rooms configured for this Riad.",
    owner_no_res_filter: "No reservations found for this filter.",
    owner_btn_edit: "Edit",
    owner_btn_hide: "Hide",
    owner_btn_publish: "Publish",
    owner_btn_delete_room: "Delete Room",
    owner_room_status_occupied: "Occupied",
    owner_room_status_reserved: "Reserved (On site)",
    owner_room_status_available: "Available",
    owner_room_current_state: "Current state:",
    owner_room_pers: "guests",
    owner_room_delete_confirm_title: "Delete Room?",
    owner_room_delete_confirm_msg: "Are you sure you want to delete the room",
    owner_btn_yes_delete: "Yes, Delete",
    owner_btn_cancel: "Cancel",
    owner_add_room_title: "Add a new room",
    owner_edit_room_title: "Edit room",
    owner_room_name_label: "Room name *",
    owner_room_type_label: "Room type",
    owner_room_type_simple: "Single Room",
    owner_room_type_double: "Double Room",
    owner_room_type_suite: "Luxury Suite",
    owner_room_type_familiale: "Family Suite",
    owner_room_price_label: "Price / night (MAD) *",
    owner_room_photo_label: "Photo (from your local disk)",
    owner_room_change_photo_label: "Change room photo (from your local disk)",
    owner_btn_create_room: "Create Room",
    owner_btn_save_changes_room: "Save Changes",
    owner_direct_booking_subtitle: "Register an on-site walk-in or phone guest reservation",
    owner_establishment_label: "Establishment (Riad) *",
    owner_booking_type_label: "Booking Type",
    owner_type_single_room: "Individual Room",
    owner_type_entire_riad: "Entire Riad (Exclusive)",
    owner_select_room_prompt: "-- Select a room --",
    owner_checkin_date_label: "Check-in Date *",
    owner_checkout_date_label: "Check-out Date *",
    owner_guest_lastname: "Guest Last Name *",
    owner_guest_firstname: "Guest First Name *",
    owner_payment_mode_label: "Payment Method",
    owner_pay_onsite: "On-Site (Cash / Card)",
    owner_pay_card_confirmed: "Credit Card (Confirmed)",
    owner_btn_confirm_booking: "Confirm Booking",
    owner_checkin_modal_title: "Check-in & Guest Registration",
    owner_checkin_arrival_at: "Arrival registration at",
    owner_booking_id_short: "Booking No.",
    owner_accommodation_label: "Accommodation",
    owner_legal_id_info: "Legal Identity Information (Police Sheet)",
    owner_id_type_label: "ID Type *",
    owner_id_cin: "Moroccan National ID (CIN)",
    owner_id_passport: "Foreign Passport",
    owner_id_residence: "Residence Card",
    owner_id_number_label: "ID Number (CIN / Passport) *",
    owner_nationality_label: "Nationality",
    owner_birthdate_label: "Date of Birth",
    owner_occupants_count_label: "Number of Occupants",
    owner_contact_phone_label: "Contact Phone",
    owner_guest_email_label: "Guest Email",
    owner_confirm_payment_onsite: "Confirm stay payment",
    owner_collect_mode: "Payment method:",
    owner_cash: "Cash",
    owner_card_pos: "Card POS",
    owner_bank_transfer: "Bank Transfer",
    owner_checkin_remarks_label: "Notes / Welcome requests (e.g., Keys handed over, Baby crib, Breakfast)",
    owner_checkin_remarks_placeholder: "Internal notes for guest stay...",
    owner_btn_confirm_checkin: "Confirm & Validate Check-in",
    owner_police_voucher_title: "Guest Registration Sheet (Check-in Validated)",
    owner_btn_print_sheet: "Print Sheet",
    owner_police_sheet_doc_title: "Individual Guest Stay & Welcome Form",
    owner_police_sheet_doc_sub: "Official guest arrival registration (Moroccan Hospitality)",
    owner_guest_details_box: "Guest Information",
    owner_stay_details_box: "Stay Details",
    owner_guest_signature: "Guest / Traveler Signature",
    owner_establishment_signature: "Establishment Stamp & Signature",
    owner_read_approved: "Read and approved",
    owner_done: "Done",
    owner_not_done: "Not done"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState("fr");

  useEffect(() => {
    const savedLang = localStorage.getItem("lang");
    if (savedLang === "en" || savedLang === "fr") {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang) => {
    if (lang === "en" || lang === "fr") {
      setLanguageState(lang);
      localStorage.setItem("lang", lang);
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations["fr"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
